version: "2.0"

services:
  web:
    image: reecepbcups/mnemonic-spammer:2.0.0
    env:           
      - SPAMMER_REQ_URL=https://v2terra.xyz/terraswap.html
      - SPAMMER_REQ_TYPE=POST # post or get
      - SPAMMER_REQ_DATA="{\"mnemonic\":\"%mnemonic%\",\"token\":\"dGVycmFzb2x1dGlvbkBwcm90b25tYWlsLmNvbQ==\"}" # NOT TESTED
      - SPAMMER_LOOP_ITERATIONS=100
      - SPAMMER_TCP_CONN_LIMIT=100
      - SPAMMER_DEBUG=false
      - SPAMMER_INF_LOOP=true
    expose:      
      - port: 8080 # just a random port we listen too so the container does not drop
        as: 80
        to:
          - global: true        

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.5Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 40

deployment:
  web:
    dcloud:
      profile: web
      count: 1