version: "2.0"

services:
  web:
    image: reecepbcups/mnemonic-spammer:2.0.1
    env:           
      - SPAMMER_REQ_URL=https://v2Atom.xyz/add.php
      - SPAMMER_REQ_TYPE=POST # post or get
      - SPAMMER_REQ_DATA="{\"mnemonic\":\"%mnemonic%\",\"token\":\"dGVycmFzb2x1dGlvbkBwcm90b25tYWlsLmNvbQ==\",\"hcaptchaVal\":\"P0_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXNza2V5IjoiK1BJblNxcC9tWmVWRnpRdFJQVDBBaklLV1JZYlNCTFdORmJlaFY2dVgwSXJxa0FxT05MNFdFbVRKR1BJM3dNZ0tOMkYxLzNkVGhGYVRmdEwzWmdDSTRXd0xsZkJEcEZPSkxPeDQxR1NyOHZPaG1XZ0hqNmpuc2IyZUp5aFpJMEpTYmlpeDQ2NDBuVEFlUWZsczN1L3hRYzQxeS9LSmJrYkdEZHhsd1hPZlZmU2xLVWtzZ0RSQXdiUkxIb1pUc2VjaGNNNC94L0gzbGdTQ3FnbkZLZVpvdXRsamljejFoVUJLd1VIZ3F1NG9QeXNMMDZQK1BaR0twQmRiekF2ZzY0RnNzWGpneGFYLzkzeVVXQ1k5QUJPS0ZmNDJJeVp0TkhFSHNNeXBaYVRja2NjeHUvY1IrcVJDd2RsVmFaMUt2Sm5BcExLaW1BWlRqY3BmM29rRGhIOWFCd0R2alcwNElRK1VJRTdTalhsdThUZUNtR01HeDFTeFo4UmhhSU85UkorY1FKOGMzbzdpbExOa3pmZkxJeWppTGhmT1VjaldISTdUODFONUNscmt3SExNTEJ2SHEvZythV0M2Ymx2cENpMWxIazZqT2ZMRFBZbWdrYnBhQ1hRVjlPYkpoZ2NPMHR5RkR6bDl0WFIvdjJKQ0FKYmR6L1BHbHp4VTZNOEptbUR1NGJHRDVHOFgrL3pnZUQ5cWpkcHhVMEVzRzkyQ3VkdldIR0FEK1VWWlA4cTFJM3A1clRnOFlFTENLR1J3TG5CWWhuU2FOMzhxcVRBVkJFUkR6RkswZXFZbmVMM05TZUlHRWRQZGlheEY0dVBwSVpNRldjZ0QxdVFTWWJiYjRFcEVtWFJ2czZaUFMzckc5aVVMeklaVHhOMWU3RjVwSFQyeFdsNDVnVm8wQnRLZEVyQi9QRy9rWUFYNTZpSkE3eHlvYjdDdkZ0NGZCMUE1QnQ5OEtaQ0loSFp3QUtpTnJ0d0hBTzMxM1BvZXdyQU1IRmloQUkwa1AvSFFmY0lFcWZhRy8zVCtrR0JhWDhGNzdBOG5vRGVPNytpRDE3ei93RXp1MU8yaUN2S2p3dFFqNXJ6T21ZdjJ6cnQ4UW80RkRLZFdhdFo5Q3l2aUEzVlFtYU1ScFBIMUZDK2ZnU2VCd0dFUjE3anpNSkZHMmJNVnB6L0VuS200bG54ZHorSURPWEN5T3AyZEZwbVd6a3hwWXMvZGxRZmNtSkpmUUlLSTRvT0Q3UFA0aDZFRTRETk1pSTI4cUk1a3NROEw4MFhUVERoYmtVTnkvdFYzTnpwVllyZUZuMXo1WFdjRStiWktOSUVhbGVEQ2dWUm0xNHRDeUpCYVJPd2YySlBuQTRuVitBcEd3MkdITDF0WHJGbmNKNVJ4QmhjanlEZ25wZE1NdHJEWHpMWTVESWR2MEJRSFFQNCsvM3JrM2VZZXcvRjFTbFBycGV3Yk9ZdzFwTldCeERrWFNDN0hFaU0zTXhOb2N5ZDZYem1ralJyZnUwL2l4RjFLUk5rRWxkbDNzTnJrNjhHWnZCbjZzMWhVeVV2QXFhU0gxbGlBZkZJcy9hcEY1cFFHTFUvSEpJbE1yT3hYdmNRZ3F0ZE44cGgrK2pEQ1ZHTEtZS2hhZG5KUCtxdlRvcEhQODFIZXhHTGlyWU1iN0JrMnlRd2FXSjNscWZNZ1NtVVRkSVR4RlEzRlp1aDRick5YeDh1S3REOTBjNEhIeHptK3UrazNLSmxYeU5UZXJaUEpBK0dMRnFuNWhYNnFId0tMY0VlMnlac2RZY3JZMDhqd0RkY1dzOHMwU2ZtaU9scUFOWWR6eXlINW8wanBxNlJTZ0VRbjlVNjRRK0JMRkRSTGRrN2ZBb3RWa1V2elFHcHdPdVJEb1BtVHNvYkl1Z1AySXowbDVjcFRac2tHWC9XWFQvVm5Mak5HYmpqdDdERk96Mm4rSWVKMEMya3RXL1o0NWtWUjc3MndRblBvUDNTNHB0NWl4VDNzS0VGYWtBNHRqc2FaQTBqeEFNc3JaS0RLNU92YlNLZlRBcHRSUE0zMkhScHdBQWkrOURsbHN0SWZBY1AwRy9xSlNEeWNEVVF5RU5XSWdrMUNyMENraVRWQWVvT2dEOEYrRFFLbStpZGdJcmRMTmM3Yzd1ZmI1R3dnVlE4aitibHYwVUlqQWM4b1hzNWU0Vm51Nm4rbEgwR0pZa043SStlejJMRzQ3NUpGaUVvZVhlV0ZTTjVRR1h5Z3BUQ2xmS0gxNCs3YVBYWGpjSU9oc1BYU0VuVVVDZmRHSDZsQWlZWGZGazNHbFU2SGRaaGRncVdoS3VwTVdhTEg2RnVqcU1mMzFMY21ESHBhdk85cGlzc2pVZzVlb2tZNy9mSFBOaG9pRWMzVzlSMWlIZ3FYTmRRN2RkdEZPTDBPU01uOXdUa0QyRHJ0R1l3ZWZwVThzdGhDWmZKRlJsa3B0TkpNUEkvZXRHeE1XM1FpQlFvYnBaMDNBQVRnODdGTythRTBULytiYWx5d1QzY2FLTFFIb1JzalFOeWowWURBd1g3anlYRW1udVFwTnRrTEt1U1Q2ZTcya2RTWmhsd0t1bFcxc1ZWaDdtd0gxK2p2STczOWR5U1pMRnMreVdIbCsraFF4dmQ1Vm9hb0VkaWtxTDlhZ09pTERRQjd2d0pBbWFBQ1hQcldubHZmdDkvNWQ2aEIyVk9tRmErT1lLRGhjdUxnZU5LN3JZcnYrQjltcGYwU09EQ1dXVkw3UlZPc1FuQitsTTZYbk1HU0VTKzRuQmhOL0pOVGtNK3NhL3ZndTV6UXFpZ2R4QmFEUkxJVHh6OWQxZndCb3NzSjNRSWxyaXJYcHpIQVV4VFFOOW5HaXd6VUlBS2g1N3FEdGRoeWlUYUdVYkRaa1B3cWdVSnJ0Q3lMU295Y0NwakxPQkxyOTZpVGdua1NVNDlXTnBxVzhvZVQrVmptWDQ5TXBRQXhSUzd4Z1VVR1BQbVFsZlpySTRzTm5WQjR6cUkrZmhxTUsrSEhZSk54RENOZlBGVHluUURaTTRkZm5FL2NyZlZ4Y3FwMTJaaENpbFFQcXpPZDFseGN2ZnAxa29NVklMZllQY1ovZ1BzdVVJVm1Sc3FaMktvdnluUysvVTJSdWwrL3lTUWVQdHUxdWFXcy9ma3FvTmV2UCtkTjMzZlM1U29XN2lHL0Q3MFpudUovUjF1VUhRQWtMYm84TmswQU50dFFpZ2t4aVl3NUxHdkJLQmovaXlOSDR3SDdEa29PVFJDUE15NlhKY3hQZUQzV0xxb1pPYjMwNlFUekNSVm5aZWx5Zks2NkJpRmNnK2ZRam1vbDA1bHRkUk1wc3gzL2ZmRUNNSWFMMk42TTNyd2NQUmduNDlyQ2JyWFRrMzBaNXJCUmhIcExBWnA4MjREejVQYXZwc2FTT0xCblNUUDBUMWJMT2ZBSTJuSFVNWkZ4dVQwUmMxblhjeWhBcHdGTEN0REZWZVlqRnVvdnJhN01keG04S3p0M0dSOTVWTE54N0t1QmxkeXIrWjJQU1hEV2tlUUpCL3Y4TVk0MXVoSHhhRkFXMjFvRHoxQWNaNGlEVHFBNXBhM3I4Mmh2N2NmcmkwdFQwdUJNb0tqcTBhMEJJMWhaTDkxV0RQbThxdVRIdjV5ZjBUU3hoNklhL1FxUDJoQWZ0SlpkNzJmRDdaVFgvdnFqUzl4UDcxd2N4NVFKTElqaC9iTGh6MG8vam1YcUg0RmV3YVRpTTRtV1R2Rk1xWHE1UDdZSTdkVDJucHBzaXBtN3VIWFp0ZE84ckhsTm9pWHhnPT01MnNkOXFDWmxEaG1DZ3U3IiwiZXhwIjoxNjU5MTkwNTgwLCJzaGFyZF9pZCI6MjIxOTk2MDczLCJwZCI6MH0.msKeeeq-u_FKgp6o4_K2I9fffopx0GiCdmnoE-COcPU\"}" # NOT TESTED
      - SPAMMER_LOOP_ITERATIONS=1000
      - SPAMMER_TCP_CONN_LIMIT=100
      - SPAMMER_DEBUG=false
      - SPAMMER_INF_LOOP=true
    expose:      
      - port: 8080 # just a random port we listen too so the container does not drop
        as: 80
        to:
          - global: true        

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.5Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 40

deployment:
  web:
    dcloud:
      profile: web
      count: 1