version: "2.0"

services:
  web:
    image: reecepbcups/mnemonic-spammer:1.0.0
    env:           
      - SPAMMER_INF_LOOP=true
    expose:      
      - port: 8080 # just a random port we listen too so the container does not drop
        as: 80
        to:
          - global: true        

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.5Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 20

deployment:
  web:
    dcloud:
      profile: web
      count: 1